export { addAction, doAction } from './hooks.js'
export { registerPlugin, getAllPlugins, getPlugin, subscribePlugins } from './registry.js'
export { configureProfileStore, getProfile, isPluginEnabled, setPluginEnabled, useProfile } from './profileStore.js'
export type { UserProfile } from './profileStore.js'
export { registerProvider, getProvider } from './contracts.js'
export type { PluginDef, PluginFactory, HostAPI, PluginDeps, PluginManifest } from './types.js'
